apiVersion: v1
kind: Service
metadata:
  name: svc-app-tc-2023
spec:
  selector:
    app: app-tc-2023
  type: NodePort
  ports:
    - port: 3333      
      targetPort: 3333      
      nodePort: 32000
